# Generated by Django 5.2 on 2025-04-22 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhooks', '0003_remove_produto_arquivo_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_entrega', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('formato', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5'), ('Carta', 'Carta')], default='A4', max_length=10)),
                ('cor_impressao', models.CharField(choices=[('PB', 'Preto e Branco'), ('Color', 'Colorido')], default='PB', max_length=10)),
                ('impressao', models.CharField(choices=[('1_LADO', 'Um Lado'), ('2_LADOS', 'Frente e Verso')], default='1_LADO', max_length=20)),
                ('gramatura', models.CharField(default='75g', max_length=10)),
                ('papel_adesivo', models.BooleanField(default=False)),
                ('tipo_adesivo', models.CharField(blank=True, max_length=50, null=True)),
                ('grampos', models.CharField(blank=True, max_length=10, null=True)),
                ('espiral', models.BooleanField(default=False)),
                ('capa_pvc', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Impressão',
                'verbose_name_plural': 'Configurações de Impressão',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('cod_op', models.CharField(max_length=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_criados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhooks.produto')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='formularios.configuracaoimpressao')),
            ],
            options={
                'verbose_name': 'Arquivo PDF',
                'verbose_name_plural': 'Arquivos PDF',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='formularios.contato'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
    ]
