# Generated by Django 5.2 on 2025-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivopdf',
            name='unidades',
            field=models.ManyToManyField(related_name='arquivos_pdf', to='formularios.unidade'),
        ),
    ]
