# Generated by Django 5.0.1 on 2025-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_arquivopdf_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivopdf',
            name='json_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='arquivopdf',
            name='link_download',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
