# Generated by Django 4.2.5 on 2025-04-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_frente', models.URLField()),
                ('capa_verso', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_frente', models.URLField()),
                ('capa_costas', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etiqueta_envio', models.URLField(blank=True, null=True)),
                ('metodo_envio', models.IntegerField(blank=True, null=True)),
                ('numero_pedido', models.IntegerField(unique=True)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('documento_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('endereco_envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.enderecoenvio')),
                ('informacoes_adicionais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.informacoesadicionais')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='webhook',
            name='assinatura',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('id_sku', models.IntegerField(blank=True, null=True)),
                ('arquivo_pdf', models.URLField()),
                ('designs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.design')),
                ('mockups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.mockup')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='webhooks.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='webhooks.webhook'),
        ),
    ]
