# Generated by Django 5.2 on 2025-04-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_remove_produto_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='arquivo_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='designs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.design'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='mockups',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.mockup'),
        ),
    ]
