# Generated by Django 5.0.1 on 2025-04-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_produto_arquivo_pdf_alter_produto_designs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookStatusEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('url_destino', models.URLField()),
                ('payload', models.TextField()),
                ('resposta', models.TextField(blank=True, null=True)),
                ('codigo_http', models.IntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks_enviados', to='webhooks.pedido')),
            ],
            options={
                'verbose_name': 'Webhook de Status Enviado',
                'verbose_name_plural': 'Webhooks de Status Enviados',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
