# Generated by Django 5.2 on 2025-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_webhookstatusenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Processing', 'Em Processamento'), ('Pending', 'Pendente'), ('Completed', 'Concluído')], default='Processing', max_length=20),
        ),
    ]
