# Generated by Django 5.2 on 2025-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_pedido_pdf_path_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('NewOrder', 'Novo Pedido'), ('Processing', 'Em Processamento'), ('Production', 'Enviado para Produção'), ('Preparing', 'Preparando Envio'), ('ReadyForPickup', 'Pronto para Retirada'), ('WaitingForPickup', 'Aguardando Retirada na Transportadora'), ('Shipped', 'Enviado'), ('InTransit', 'Em Trânsito'), ('Delivered', 'Entregue'), ('Pending', 'Pendente'), ('Completed', 'Concluído'), ('Cancelled', 'Cancelado')], default='NewOrder', max_length=20),
        ),
    ]
