# Generated by Django 5.2 on 2025-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo Pedido', 'Novo Pedido'), ('Enviado para Produção', 'Enviado para Produção'), ('Preparando Envio', 'Preparando Envio'), ('Pronto para Retirada', 'Pronto para Retirada'), ('Aguardando Retirada da Transportadora', 'Aguardando Retirada da Transportadora'), ('Enviado', 'Enviado'), ('Em Trânsito', 'Em Trânsito'), ('Entregue', 'Entregue'), ('Retornando - Erro na Entrega', 'Retornando - Erro na Entrega'), ('Cancelado', 'Cancelado')], default='Novo Pedido', max_length=50),
        ),
    ]
