# Generated by Django 5.2 on 2025-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_webhookendpointconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookstatusenviado',
            name='tentativa_numero',
            field=models.IntegerField(default=1),
        ),
    ]
