# Generated by Django 5.2 on 2025-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_webhookstatusenviado_tentativa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpointconfig',
            name='access_token',
            field=models.CharField(blank=True, help_text='Token de autenticação opcional para incluir na URL', max_length=255, null=True),
        ),
    ]
