# Generated by Django 5.2 on 2025-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_webhookendpointconfig_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de E-mail')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Destinatário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-mail de Notificação',
                'verbose_name_plural': 'E-mails de Notificação',
                'ordering': ['nome'],
            },
        ),
    ]
