# Generated by Django 5.0.1 on 2025-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_formulario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('escola', 'zeroHum'), ('escola', 'elite'), ('escola', 'coleguium'), ('escola', 'pensi')], default='form1', help_text='Define o tipo de formulário que o usuário tem acesso', max_length=10, verbose_name='Tipo de Formulário'),
        ),
    ]
