# Generated by Django 5.0.1 on 2025-04-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_tipo_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_formulario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('zerohum', 'ZeroHum'), ('elite', 'Elite'), ('coleguium', 'Coleguium'), ('pensi', 'Pensi')], default='zerohum', help_text='Define o tipo de formulário que o usuário tem acesso', max_length=10, verbose_name='Tipo de Formulário'),
        ),
    ]
